/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking_app;

import java.sql.*;
import javax.swing.*;
import java.time.*;
import com.sun.istack.internal.logging.Logger;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CLEMENT O. A-U
 */
public class SearchAccount_Panel extends javax.swing.JPanel {

    Connection conn;
    PreparedStatement ps;
    final String url = "jdbc:mysql://localhost:3306/banking_app";
    final String user = "root";
    final String pass = "";
    String s;

    /**
     * Creates new form SearchAccount_Panel
     */
    public SearchAccount_Panel() {
        initComponents();
        DoConnect();
    }

    public void DoConnect() {
        try {
            conn = DriverManager.getConnection(url, user, pass);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountNumber = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AccountTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, 170, 20));

        jLabel2.setText("Account Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 110, 30));

        accountNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                accountNumberFocusLost(evt);
            }
        });
        add(accountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 40));

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });
        add(goButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        AccountTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        AccountTable.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        AccountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "A/C Name", "A/C No", "A/C Type", "A/C Balance"
            }
        ));
        jScrollPane1.setViewportView(AccountTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 420, 150));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/images/wp2070593-wallpaper-hd-music.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 410));
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        String search = "select * from account where acct_no = ? order by trans_date desc limit 1";
        String tacct_no = accountNumber.getText();
        try {
            ps = conn.prepareStatement(search, ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ps.setString(1, tacct_no);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                DefaultTableModel model = (DefaultTableModel) AccountTable.getModel();
                if (model.getRowCount() == 0) {
                    String tacct_name = rs.getString("acct_name");
                    String tacct_type = rs.getString("acct_type");
                    String tacct_bal = Double.toString(rs.getDouble("acct_balance"));
                    model.addRow(new String[]{tacct_name, tacct_no, tacct_type, tacct_bal});
                }

            } else {
                JOptionPane.showMessageDialog(null, "Account Not Found!");
                accountNumber.setText("");
                DefaultTableModel model = (DefaultTableModel) AccountTable.getModel();
                model.setRowCount(0);
//                model.addRow(new String[]{"", "", "", ""});
            }

        } catch (SQLException se) {
            se.printStackTrace();
        }
    }//GEN-LAST:event_goButtonActionPerformed

    private void accountNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accountNumberFocusLost
        // TODO add your handling code here:
//        String getAcct = "select * from account where acct_no = ? order by trans_date desc";
//        String tacct_no = accountNumber.getName();
//        try {
//            ps = conn.prepareStatement(getAcct);
//            ps.setString(1, tacct_no);
//            ResultSet rs = ps.executeQuery();
//
//            if (rs.next()) {
//
//            }
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }
    }//GEN-LAST:event_accountNumberFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AccountTable;
    private javax.swing.JTextField accountNumber;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
